version: "3"

services:
    php:
        build:
            context: .
            dockerfile: dev.Dockerfile
        volumes:
            - .:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
